server:
  port: 9090

spring:
  security:
    user:
      name: "dumenflix"
      password: "123456"
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/dumen_flix
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

dumenflix:
  jwt:
    secret-key: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7
    issuer: dumenflix